services:
  migrations:
    image: wonsky/olx-bot-migrations
    env_file:
      - migrations.env
    depends_on:
      postgres:
        condition: service_healthy
    command: python /app/scripts/run_migrations.py migrate
    healthcheck:
      test: ["CMD", "python", "/app/scripts/run_migrations.py", "migrate"]
      interval: 30s
      timeout: 10s
      retries: 5

  service:
    image: wonsky/olx-bot
    restart: unless-stopped
    env_file:
      - telegram.env
    depends_on:
      migrations:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy

  worker:
    image: wonsky/olx-bot-worker
    restart: unless-stopped
    env_file:
      - worker.env
    depends_on:
      migrations:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5001:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
