services:
  service:
    image: wonsky/olx-bot
    restart: unless-stopped
    env_file:
      - telegram.env
    depends_on:
      - postgres

  worker:
    image: wonsky/olx-bot-worker
    restart: unless-stopped
    env_file:
      - worker.env
    depends_on:
      - service
      - postgres

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5001:5432"

volumes:
  postgres_data:
