"""add last_updated and last_got_item to monitoring_tasks

Revision ID: 7266955a9bd0
Revises: 98f85d0154fb
Create Date: 2025-07-15 20:30:09.420164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7266955a9bd0'
down_revision: Union[str, Sequence[str], None] = '98f85d0154fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_records', sa.Column('item_url', sa.String(), nullable=True))
    op.drop_index(op.f('ix_flat_records_flat_url'), table_name='item_records')
    op.drop_index(op.f('ix_flat_records_id'), table_name='item_records')
    op.drop_index(op.f('ix_flat_records_source_url'), table_name='item_records')
    op.create_index(op.f('ix_item_records_id'), 'item_records', ['id'], unique=False)
    op.create_index(op.f('ix_item_records_item_url'), 'item_records', ['item_url'], unique=True)
    op.create_index(op.f('ix_item_records_source_url'), 'item_records', ['source_url'], unique=False)
    op.drop_column('item_records', 'flat_url')
    op.add_column('monitoring_tasks', sa.Column('last_updated', sa.DateTime(), nullable=False))
    op.alter_column('monitoring_tasks', 'chat_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('monitoring_tasks', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_monitoring_tasks_url'), table_name='monitoring_tasks')
    op.drop_index(op.f('ix_monitoring_tasks_chat_id'), table_name='monitoring_tasks')
    op.create_index(op.f('ix_monitoring_tasks_chat_id'), 'monitoring_tasks', ['chat_id'], unique=True)
    op.drop_column('monitoring_tasks', 'created_at')
    op.drop_column('monitoring_tasks', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoring_tasks', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('monitoring_tasks', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_monitoring_tasks_chat_id'), table_name='monitoring_tasks')
    op.create_index(op.f('ix_monitoring_tasks_chat_id'), 'monitoring_tasks', ['chat_id'], unique=False)
    op.create_index(op.f('ix_monitoring_tasks_url'), 'monitoring_tasks', ['url'], unique=False)
    op.alter_column('monitoring_tasks', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('monitoring_tasks', 'chat_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('monitoring_tasks', 'last_updated')
    op.add_column('item_records', sa.Column('flat_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_item_records_source_url'), table_name='item_records')
    op.drop_index(op.f('ix_item_records_item_url'), table_name='item_records')
    op.drop_index(op.f('ix_item_records_id'), table_name='item_records')
    op.create_index(op.f('ix_flat_records_source_url'), 'item_records', ['source_url'], unique=False)
    op.create_index(op.f('ix_flat_records_id'), 'item_records', ['id'], unique=False)
    op.create_index(op.f('ix_flat_records_flat_url'), 'item_records', ['flat_url'], unique=True)
    op.drop_column('item_records', 'item_url')
    # ### end Alembic commands ###
