services:
  db:
    image: wonsky/topn-db:prod
    restart: unless-stopped
    env_file:
      - db_service.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://0.0.0.0:8000/health')"]
      interval: 120s
      timeout: 10s
      retries: 5
      start_period: 10s
    ports:
      - ${DB_SERVICE_PORT:-8000}:8000

  telegram:
    image: wonsky/topn-telegram:prod
    restart: unless-stopped
    env_file:
      - telegram.env
    depends_on:
      db:
        condition: service_healthy

  worker:
    image: wonsky/topn-worker:prod
    restart: unless-stopped
    env_file:
      - worker.env
    depends_on:
      db:
        condition: service_healthy

  postgres:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - postgres.env
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DB_SERVICE_PORT:-5001}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
